### ISSUE TITLE
Pulsar Updates

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/admin-training#101]
- [x] https://github.com/galaxyproject/admin-training/issues/96, https://github.com/galaxyproject/training-material/pull/2199
- [x] Record slides (automated or manual?)
- [x] Record training

**Comment by Slugger70** [comment]
I'll get onto this soon.. :)

**Comment by Slugger70** [comment]
Slides have been updated. I might record these myself instead of automatically.
Tutorial needs testing, will be doing that today.
Then video..

**Comment by hexylena** [comment]
Yeah bril if you do em yourself! I think I want to get to the point of automated versions being available but upgrading to humans were possible / not too outdated.
