### ISSUE TITLE
Securely Installing Galaxy lecture

### ISSUE THREAD

**Issue by afgane** [galaxyproject/admin-training#102]
Several Galaxy members have been working with [TrustedCI](https://www.trustedci.org/) to create a template for a System Security Plan document that will provide guidelines for best-practice deployments that improve system security. Could we find an hour-long slot in the Jan 2021 admin training schedule to go over this document and help admins orient themselves with it?

**Comment by hexylena** [comment]
Hey @afgane, @mvdbeek mentioned this to me during admin training planning. I told him I'd love to have it for admins and documentation.

However, before we commit to inclusion, I'd love to see the associated training material first. When do you think this will be ready?

**Comment by afgane** [comment]
This would be more of a talk than interactive training. A member from TrustedCI group (Anurag Shankar) is willing to deliver (most) of the hour-long talk and has agreed to put together an outline for the talk by early December. Does that fit?

**Comment by afgane** [comment]
Anurag provided the following outline for the talk:

1. Intro: At a high level, (5 min)
  Establish context, your recent compliance-oriented projects driving security assessment need and your engagement application.
  Talk briefly about Trusted CI.
  Talk about the process we went through, at a high level.
  Talk about where the process comes from.
2. What is a SSP? (5 min)
  Take a quick look at the SSP.
  Talk about NIST 800-53.
3. The Galaxy SSP (35 min)
  Go over it section by section.
  Talk about the measures they should have in place and what security Galaxy provides

**Comment by hexylena** [comment]
Ok, sounds fine. There will need to be a recording, we're not doing anything live obviously, so just let us know when it's available and we can add it to the schedule.

If you all can subtitle this, then if it's ready by january 15th that's fine! :) If not, then we'll need it by Dec 31st to ensure it's subtitled in time.

**Comment by afgane** [comment]
Here is a link to the video: https://gxy-shared.s3.amazonaws.com/Securing_your_galaxy.mp4

**Comment by hexylena** [comment]
Awesome!!!

 Is there any chance y'all'll have time to write subtitles for that? (I.e.
upload to youtube, use the automatic subs, make sure they're correct,
download the result)

Enis Afgan <notifications@github.com> schrieb am Di., 29. Dez. 2020, 18:18:

**Comment by afgane** [comment]
Uploaded to YouTube and enabled auto-captions: https://www.youtube.com/watch?v=CQLUap74DVA

**Comment by hexylena** [comment]
Hi @afgane, that's great. Have you confirmed the subtitles are completely correct? Or just enabled the automatic ones?

**Comment by afgane** [comment]
It's just the auto-captions.

**Comment by hexylena** [comment]
Can you ensure they're correct before the 15th?

**Comment by hexylena** [comment]
Just following up here @afgane, will your team have time to ensure the captions are correct before the event?

**Comment by afgane** [comment]
Was planning on figuring it out but given it hasn't happened in the past week, it's not likely it will happen in the next 2 days. The captions are not necessarily perfect but it'll be fine.

**Comment by hexylena** [comment]
That's too bad to hear since we're targeting a global audience of ESL speakers and folks with potential accessibility issues. I'll watch it at some point soon since I'm curious about the content, and can flag anything wrong if you could patch those changes back in. Would that be an option for you?

Additionally:

- [ ] is the document publicly available somewhere? Or is it still "in the coming weeks"? Do you have a date? 
- [ ] If you want people to apply, you might want to put that URL in the video description
- [ ] are the slides available? People ask for those constantly.
- [ ] is k8s the only deployment type analysed? I haven't had time to watch this yet but I see a slide saying it's the selected deployment model that's being analysed. (I guess because of anvil.)

**Comment by afgane** [comment]
- The planned release for the document is Feb 2, 2021 so the Outreach team has had some time to incorporate it into their schedule.
- Not sure what you mean by asking if we want people to apply. Apply for what?
- The slides are [here](https://docs.google.com/presentation/d/1aMYzRX3pbTPpFHNqpA_BtWPADUfpWQ11YJ2JXiwVwp0/edit?usp=sharing) and [here](https://ea-tmp.s3.amazonaws.com/Galaxy-Anurag-Slides.pdf).
- Yes, the focus of the SSP is on the K8s-based Galaxy deployments, as stated in the video and the document. 

btw, as asked, we delivered the video before Dec 31 to give time for subtitling:
> If you all can subtitle this, then if it's ready by january 15th that's fine! :) If not, then we'll need it by Dec 31st to ensure it's subtitled in time.

**Comment by hexylena** [comment]
Thanks for the answers. I forgot i had offered that, that's on me. Cheers!
