### ISSUE TITLE
Slides Needing Video Compatible Speaker Notes

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/admin-training#104]
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/database/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/uwsgi/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/systemd-supervisor/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/production/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/tool-management/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/users-groups-quotas/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/cvmfs/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/gxadmin/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/monitoring/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/connect-to-compute-cluster/slides.html
- [x] https://training.galaxyproject.org/training-material/topics/admin/tutorials/maintenance/slides.html

**Comment by ic4f** [comment]
I've added the ansible tutorial slides to the list - I don't think they are ready.

**Comment by hexylena** [comment]
@ic4f could you please elaborate on why you don't think they're ready? it would be helpful.

**Comment by ic4f** [comment]
@hexylena I meant speaker notes, but I was wrong! This has been all taken care of in 8d7978b3c770c7402dfa1ec13691d39922f63453 - I must have been thinking of the version prior to that. Sorry!

**Comment by hexylena** [comment]
No worries! :)

**Comment by cat-bro** [comment]
I'm working on speaker notes for https://training.galaxyproject.org/training-material/topics/admin/tutorials/tool-management/slides.html

**Comment by martenson** [comment]
I finished the last two [here](https://github.com/galaxyproject/training-material/pull/2152/commits/ebb951650e762dca3f3d6087d1371f70916e0fff) and [there](https://github.com/galaxyproject/training-material/pull/2152/commits/75f0b12a8e07d382a67a7505ae69dab8c320f4fc).

As usual, thanks @hexylena for leading the charge, as usual.

**Comment by hexylena** [comment]
Thanks so much @martenson for finishing it, i didn't have it in me.
Fantastic!!

Martin Cech <notifications@github.com> schrieb am Di., 5. Jan. 2021, 21:34:
