### ISSUE TITLE
Correct Video Captions

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/admin-training#115]
Since we're doing video for this training, they absolutely need to be captioned, and captioned correctly. We have participants from all around the world and some of us have strong accents or speak quickly, we want these videos to be intelligible to all.

## Process

Once videos are uploaded to youtube, ~1-2h later we get the automatic captions. They're quite good but not perfect and need a lot of polishing. This is where we need YOUR help. I'll be transferring the text google produces into a google document. I need people to work on these, listening to the video, and ensuring that the content is correct. , , etc. We don't need to catch 100% of capitalisation issues, but we should get most.

## We Need You

Steps:
1. Open the Video (link under each section.)
2. Make Corrections
    - Listen to the contents, and wherever you have corrections, correct the text.
    - You do NOT need to use suggestion mode.
    - Check for and *add* missing sentence breaks (. ? !)
    - Ensure "code" bits are correct (e.g. 'group_vars', not 'group vars')
    - Fix capitalisation errors (i, galaxy, ansible)
    - Fix spelling errors
    - **DO NOT** Fix grammatical errors, Remove Uhh/Umm/other filler words.
2. When you’re done with a block of work
    - Highlight it with a colour
    - We don’t expect one person to do the whole thing unless they’re motivated, some of these videos are quite long.
3. When a video is completely corrected, comment on the GitHub Issue saying it’s done. 
    - One of us will check that the text is highlighted and remove the section from this document
    - Helena or Saskia will put the text back to the video in YouTube.

## Videos Needing Caption Corrections

Below is a list of videos that need their text checked, and the relevant portion of a google doc with the text. When you feel good about a section, please just colour code it so anyone else working on parts of the video won't duplicate work. 

- [x] [Ansible Slides](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.7x6birjl4wtc)
- [x] [Ansible](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.jqi52u4izu8p)
- [x] [Ansible Galaxy](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.1b4fy0vy47o3) (Please split this with each other! It's a lot of text.)
- [x] [Ephemeris](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.jkhk15f9y4b)
- [x] [CVMFS](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.f82yztl6oglv)
- [x] [Singularity](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.4hxix7z8loyq)
- [x] [Metrics](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.c848fb8ftsme)
- [x] [Week Overview](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.3fo48khat5rk)
- [x] [Pulsar Tutorial](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.w9wsdmfaqu7f)
- [x] [Pulsar Slides](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.hoi7l6wgasxp)
- [x] [Interactive Tools](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.ce009opm55ba)
- [x] Dropbox
- [x] [Installing Galaxy with Ansible](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.2lv83wf1pp6u)
- [x] [Compute Cluster](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.tq1q3zoszoec)
- [x] [Mapping Jobs](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.yqkqhrby1nyj)
- [x] [storage management pt2](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.zdjt9jrimwew)
- [x] [monitoring](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.9y9b0km3yb6c)
- [x] [tiaas](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.rvlc1zh09m2d)
- [x] [Securing your (k8s based) Galaxy](https://docs.google.com/document/d/1qD5wRIImk66iMmnH4CvO6B4NQW8Q5ZTx4DyePHEN5Bc/edit#heading=h.6aufddmd5z1p)

**Comment by shiltemann** [comment]
ok, I did the captions for the Pulsar slides :+1: (it was pretty good already, mainly just adding punctuation and capitalization)

**Comment by martenson** [comment]
Are we going to time the captions?

**Comment by hexylena** [comment]
This is done automatically by google, they have a magic button that syncs the text with the audio.

**Comment by abretaud** [comment]
I'm done with gxit captions :heavy_check_mark:

**Comment by eancelet** [comment]
Done for Ephemeris. I'm curious about how google handles the corrections.

**Comment by hexylena** [comment]
I've pasted the updates for those three back in, you can check if you like, but, it seems to have aligned them essentially right where they already were. It's so easy.

**Comment by Slugger70** [comment]
I'm done with Ansible (tutorial) captions

**Comment by hexylena** [comment]
@Slugger70 I think the ansible one could use more punctuation, sentence splits, and capitalisation so I'll leave it open for now. Thanks for checking the english though!

**Comment by Slugger70** [comment]
ok

**Comment by cat-bro** [comment]
Singularity is done

**Comment by simonbray** [comment]
Have done the Dropbox one

**Comment by simonbray** [comment]
Also the pulsar (tutorial) one

**Comment by beatrizserrano** [comment]
I've just finished Metrics :)

**Comment by Slugger70** [comment]
Finished CVMFS tutorial.

**Comment by hexylena** [comment]
Almost done, saskia's halfway done with Monitoring, and maybe someone can find time to work on the security video?
