### ISSUE TITLE
Tapas 2022 Planning & Dissemination

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/admin-training#136]
- [x] Registration form https://forms.gle/s7UbQeEwToM8VBqE8
- [ ] Create hub event
	- [ ] Notify people registered to the "please let me know about the next event" form
	- [ ] Disseminate to mailing lists / relevant places.
- [ ] Organise infrastructure
  - @Slugger70 can provide 40 x "main" machines
  - @gmauro ?
  - @natefoo ?
- [ ] Git Lesson
- [ ] Diff tutorial
- [ ] TUS / Celery Updates @natefoo 
- [ ] Pgcleanup role?
- [ ] Setup Infra
	- [ ] Deploy
	- [ ] Provision
	- [ ] Test

**Comment by natefoo** [comment]
I'm told Jetstream 2 will be online very soon, and we'll have the capacity to allocate VMs out of it for a week.
