### ISSUE TITLE
Jenkins & Automation

### ISSUE THREAD

**Issue by sanjaysrikakulam** [galaxyproject/admin-training#145]
<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-2c308e56-7fff-8f61-1b10-bdca3aeed8ef">

Jenkins & Automation |  |
-- | --
Goals | Continuous integration and deployment of Galaxy and other services
Why | To automate through CI/CD infrastructure
Dependencies | Galaxy
Time | 
Slides | 
Exercises | https://training.galaxyproject.org/training-material/topics/admin/tutorials/jenkins/tutorial.html

</div>

To Dos:
 - [ ] create the tutorial
 - [ ] update the presentation and tutorial
 - [ ] test the hands-on

**Comment by hexylena** [comment]
I'm cancelling this one. it wasn't terribly useful, jenkins is terrible.
