### ISSUE TITLE
Recording Job Metrics

### ISSUE THREAD

**Issue by sanjaysrikakulam** [galaxyproject/admin-training#148]
<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-2c308e56-7fff-8f61-1b10-bdca3aeed8ef">

Recording Job Metrics |  |
-- | --
Goals | Recording Galaxy job metrics
Why | Helps you plan for expansions of your Galaxy server, to optimise cluster allocation etc.
Dependencies | Galaxy, Connecting Galaxy to a compute cluster, jobconf, job destinations
Time | 
Slides | 
Exercises | https://training.galaxyproject.org/training-material/topics/admin/tutorials/connect-to-compute-cluster/tutorial.html#recording-job-metrics

</div>

To Dos:
 - [ ] create the tutorial
 - [ ] update the presentation and tutorial
 - [ ] test the hands-on

**Comment by hexylena** [comment]
This is no longer a separate tutorial, so we won't track the card.
