### ISSUE TITLE
post-training improvements

### ISSUE THREAD

**Issue by martenson** [galaxyproject/admin-training#18]
Based on the assumption that many of the admins will also be the to-go resource for their users we should provide materials for **short session with advanced usage** (scratchbook, visualize/display, history search/filtering + multiview, collection manipulations etc.)

For next iteration we should make sure everybody is using same (or very similar) deployment environment. Troubleshooting heterogenous laptops was unnecessary overhead. We should also make sure network is permissive (e.g. ssh port) and performing as well as the VMs for participants (e.g. FTP port).

**Comment by martenson** [comment]
We should incorporate into materials at least quick mention of the topic list that has been created in https://github.com/martenson/dagobah-training/issues/6

**Comment by martenson** [comment]
We should polish and integrate the cheatsheet https://github.com/martenson/dagobah-training/pull/17 by @stevekm

**Comment by Slugger70** [comment]
We should add in an ansible script to each section to perform the tasks that have been done in that session. It should also list all the requirements for getting the system to the start of the session.. (i.e. Previous session's ansible scripts..)

**Comment by stevekm** [comment]
I can try to work more on the cheatsheet if that is helpful, though I'm a little swamped with other projects right now so I'm not sure when I'll get to it. @Slugger70 's suggestion of an Ansible script for each section sounds good, though I was also thinking it would be really helpful for each section to have a full/partial copy of the config & ini files that are being edited, before and during each step, the same way they are listed here: http://planemo.readthedocs.io/en/latest/writing_standalone.html
This way, you'll have a record of what the files are supposed to look like by the end of the exercises.

**Comment by hexylena** [comment]
> admins will also be the to-go resource

Many ideas listed in https://github.com/galaxyproject/admin-training/issues/6 (fantastic!)

> heterogenous laptops was unnecessary overhead

fixed 

> ansible script to each section to

fixed.
