### ISSUE TITLE
Participant selected topics	

### ISSUE THREAD

**Issue by martenson** [galaxyproject/admin-training#6]
### A list of more obscure topics participants are interested in

- [x] galaxy development (Moved to separate training.)
- [ ] launching a community
- [ ] IRIDA platform from Canada as an example of using Galaxy's backend without the interface.
- [ ] Migrating an instance on a stand alone server onto a HPC -- besides changing the config files to setup the runners, what other considerations should be taken
- [x] Interactive Environments: Jupyter notebooks (gxit)
- [ ] Getting data out of galaxy
- [ ] Archiving analyses (e.g. when paper is published, etc.)
- [ ] Collections
- [ ] Managing/Organizing the tool menu
- [x] Writing dynamic job's destinations (compute cluster)
- [ ] Overview of job working directory content (galaxy script, job script, metadata...)
- [x] Galaxy update best practices, including stopping/pausing jobs, etc.
- [ ] Debugging workflows, tools for users, including configuring galaxy to enable easier debugging, eg keeping job output dirs. Debugging tool output names in workflows.
- [x] Managing Data libraries
- [ ] Writing workflows: best practices.
- [ ] Including naming outputs, workflow version control (within Galaxy? git?), user and developer documentation for workflows (they are really pipelines, and need docs). Handling required parameters for tools in a workflow (marking them in UI? failing early?)
- [x] Using the API (bioblend)
- [x] sharing user contributed admin related scripts
- [ ] Testing tools and workflows: setting up continuous integration; common set of small, medium and large test input files that can be used across tools and workflows.

### Already discussed

- tool HTML whitelist 
- External authentication
- Active Directory authentication -- also how this affects ownership and sharing datasets.
- Reports webapp
- Conda environments for installing Galaxy, for running jobs and handle tools dependencies
- Backup best practices

**Comment by Slugger70** [comment]
We should probably mention the whitelist to the intro participants too.. It's simple and won't take long..

**Comment by clijeron** [comment]
Active Directory authentication --  also how this affects ownership and sharing datasets.

Migrating an instance on a stand alone server onto a HPC -- besides changing the config files to setup the runners, what other considerations should be taken?

Backup best practices?

**Comment by martenson** [comment]
@clijeron I added your items to the top level post, thank you!

**Comment by clijeron** [comment]
I think most people running HPC have the same issues. It would be good to address these when talking about deploying Galaxy on a cluster:

1. Old OS Version (i.e: CENTOS 6.5 with a very specific kernel version)

2. SLURM as the job manager --- Best practices:  Is it best to set a partition or group of servers for Galaxy jobs only rather than share with other users submitting jobs via CLI.

3. Our Lustre file system authenticates via AD just like our cluster.   What would be the best way to setup Galaxy under these conditions --

**Comment by pdblood** [comment]
Interactive Environments: Jupyter notebooks

**Comment by lparsons** [comment]
* Getting data out of galaxy
* Archiving analyses (e.g. when paper is published, etc.)
* Collections
* External authentication
* Managing/Organizing the tool menu

**Comment by laure182** [comment]
- Writing dynamic job's destinations
- Conda environments for installing Galaxy, for running jobs and handle tools dependencies
- Overview of job working directory content (galaxy script, job script, metadata...)

**Comment by tshtatland** [comment]
Galaxy update best practices, including stopping/pausing jobs, etc.

**Comment by tshtatland** [comment]
Debugging workflows, tools for users, including configuring galaxy to enable easier debugging, eg keeping job output dirs.

**Comment by laure182** [comment]
Managing Data libraries

**Comment by tshtatland** [comment]
Writing workflows: best practices.
Including naming outputs, workflow version control (within Galaxy? git?), user and developer documentation for workflows (they are really pipelines, and need docs).

**Comment by lparsons** [comment]
Using the API and sharing user contributed admin related scripts

**Comment by tshtatland** [comment]
Testing tools and workflows: setting up continuous integration; common set of small, medium and large test input files that can be used across tools and workflows.

**Comment by martenson** [comment]
I updated the top level post with all comments.

**Comment by blankenberg** [comment]
building paired collections?

**Comment by joe-of-all-trades** [comment]
More explanation on how pulsar works. For example, I want to offload TOPHAT2 operation from the Galaxy server to a remote Pulsar server. How do I tell Pulsar to run TOPHAT2 on the dataset against a specific genome using multiple cores?  Do I simply need to configure this on the galaxy server and the dependencies ( TOPHAT2, and genome ) will be fetched automatically on the Pulsar server?

**Comment by martenson** [comment]
Results of strawpoll.
![screenshot 2016-11-14 11 23 41](https://cloud.githubusercontent.com/assets/1814954/20277197/d5f7d73e-aa5c-11e6-84e9-1901c683088d.png)
