### ISSUE TITLE
Ansible Updates

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/admin-training#98]
- [x] any updates / fixes needed?
- [x] Record slides (automated or manual?)
- [x] Record training

**Comment by martenson** [comment]
After review me and @ic4f think that the [auto-video](https://training.galaxyproject.org/training-material/videos/#video-admin-ansible) made from the slides is sufficient. Checking it off.

**Comment by hexylena** [comment]
Would it be worth considering to do this manually this time? It's the very
first video students will see. I think it might make sense to come from a
human to give a good impression? Thoughts?

Martin Cech <notifications@github.com> schrieb am Mo., 11. Jan. 2021, 18:15:

**Comment by ic4f** [comment]
@hexylena It does start just reading off the first few slides. After that it's fine. However, if it'll make a difference to have a human do this video, then yes, let's record it. I can do it.

**Comment by hexylena** [comment]
Its also the voice which is so good, but not human. i just want to put our
best foot forward maybe?

Sergey Golitsynskiy <notifications@github.com> schrieb am Mo., 11. Jan.
2021, 18:27:
